#!/bin/bash

if [[ $# -lt 1 ]]; then
	echo "Not enough parameters"
	exit 1
fi

input="/home/etf/Desktop/TestCases/${1}/src"
output="/home/etf/Desktop/TestCases/${1}/o"

echo "Assembling"
echo "----------------------------------------------"
cd TwoPassAssembler/
./assemble_script ${input} ${output}
cd ..
echo "----------------------------------------------"
echo "Emulating"
echo "----------------------------------------------"
cd LinkerAndEmulator/
./link_script ${output}
cd ..
echo "----------------------------------------------"