#!/bin/bash
if [[ ! -d $1 ]]; then
	echo "${1} not a directory"
	exit 1
fi
if [[ ! -d $2 ]]; then
	echo "${2} not a directory"
	exit 1
fi

for file in $(ls $1)
do
	if [[ -r ${1}/${file} ]]; then
	 	echo ${file}
		./TwoPassAssembler ${1}/${file} "${2}/${file}.output"
	else
		echo "$file cant be read"
	fi 
done